In [2]:
import numpy as np
a=np.arange(10).reshape(2,5)

In [3]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
a.astype(float)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [23]:
a=np.array(["aaa","bbb"])
a.shape
a.reshape(2,1)

array([['aaa'],
       ['bbb']], dtype='<U3')

In [6]:
print(a)

['aaa' 'bbb']


In [21]:
a=np.array([["aaaa",45,13],[12,12]])
a.shape

(2,)

In [19]:
print(a)

[['aaaa' '12']
 ['12' '12']]
