In [1]:
import numpy as np
np.arange(12).reshape(6,2).itemsize


8

In [2]:
np.arange(0,2,.5)

array([0. , 0.5, 1. , 1.5])

In [5]:
np.linspace(0,2,9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
a=np.full([2,2],5)
b=np.arange(4).reshape(2,2)

In [8]:
np.dot(a,b)

array([[10, 20],
       [10, 20]])

In [9]:
a*b

array([[ 0,  5],
       [10, 15]])

In [10]:
a**2

array([[25, 25],
       [25, 25]])

In [11]:
a*2

array([[10, 10],
       [10, 10]])

In [2]:
print(a)

NameError: name 'a' is not defined

In [21]:
import numpy as np
a=np.array([['a'],[1,2]])
a

array([list(['a']), list([1, 2])], dtype=object)

In [22]:
a=((1,2))+(1,3)

In [23]:
a

(1, 2, 1, 3)